export const GET_TABLE_NAME = 'GET_TABLE_NAME';
export const FETCH_TABLE_NAME_SUCCEEDED = 'FETCH_TABLE_NAME_SUCCEEDED';
export const FETCH_TABLE_NAME_FAILED = 'FETCH_TABLE_NAME_FAILED';
export const FETCH_TABLE_NAME_REQUESTED = 'FETCH_TABLE_NAME_REQUESTED';


export const FETCH_LEFT_COUNT = 'FETCH_LEFT_COUNT';
export const FETCH_RIGHT_COUNT = 'FETCH_RIGHT_COUNT';
export const FETCH_LEFT_COUNT_SUCCEEDED = 'FETCH_LEFT_COUNT_SUCCEEDED';
export const FETCH_RIGHT_COUNT_SUCCEEDED = 'FETCH_RIGHT_COUNT_SUCCEEDED';
export const FETCH_LEFT_COUNT_FAILED = 'FETCH_COUNT_LEFT_FAILED';
export const FETCH_RIGHT_COUNT_FAILED = 'FETCH_COUNT_RIGHT_FAILED';
export const AP4_METRIC_INDICATOR_NUMBER_CLICK = 'AP4_METRIC_INDICATOR#NUMBER_CLICK';
export const AP4_FILTER = 'AP4_FILTER';

export const CARD_CLICKED = 'CARD_CLICKED';

export const USER_FETCHED = 'USER_FETCHED';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';


